spring:
  datasource:
    url: jdbc:h2:mem:bank
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


server:
  error:
    include-message: always
    include-stacktrace: on_param
    include-binding-errors: on_param
